---
# Install and configure Duo Security two-factor authentication for SSH logins

- name: add the Duo GPG key
  ansible.builtin.apt_key:
    url: https://duo.com/DUO-GPG-PUBLIC-KEY.asc
    state: present
  become: yes

- name: add Duo source to apt
  ansible.builtin.template:
    src: duosecurity.list.j2
    dest: /etc/apt/sources.list.d/duosecurity.list
  become: yes

- name: install prerequisites
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - libssl-dev
    - libpam-dev
  become: yes

- name: install Duo Unix SSH integration
  ansible.builtin.apt:
    name: duo-unix
    state: present
    update_cache: yes
  become: yes

- name: Duo configuration file
  ansible.builtin.template:
    src: pam_duo.conf.j2
    dest: /etc/duo/pam_duo.conf
    owner: sshd
    group: root
    mode: 0600
  become: yes

- name: configure sshd
  ansible.builtin.lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }}    {{ item.value }}"
    insertbefore: "^Subsystem"
    validate: /usr/sbin/sshd -t -f %s
  loop:
    - key: "UsePam"
      value: "yes"
    - key: "ChallengeResponseAuthentication"
      value: "yes"
    - key: "UseDNS"
      value: "no"
  notify: duo restart sshd
  become: yes

- name: configure PAM
  when: not duo_pam_manual_config|bool
  become: yes
  block:
    - name: create /etc/pam.d/common-auth-duo
      ansible.builtin.template:
        src: common-auth-duo.j2
        dest: /etc/pam.d/common-auth-duo
        owner: root
        group: root
        mode: 0644

    - name: configure Duo for use with login
      ansible.builtin.lineinfile:
        dest: /etc/pam.d/login
        state: present
        regexp: "^#?@include common-auth"
        line: "@include common-auth-duo"
        create: no
      when: duo_pam_use_login|bool

    - name: configure Duo for use with other authentication needs
      ansible.builtin.lineinfile:
        dest: /etc/pam.d/other
        state: present
        regexp: "^#?@include common-auth"
        line: "@include common-auth-duo"
        create: no
      when: duo_pam_use_other|bool

    - name: configure Duo for use with sshd
      ansible.builtin.lineinfile:
        dest: /etc/pam.d/sshd
        state: present
        regexp: "^#?@include common-auth"
        line: "@include common-auth-duo"
        create: no
      when: duo_pam_use_ssh|bool

    - name: configure Duo for use with sudo
      ansible.builtin.lineinfile:
        dest: /etc/pam.d/sudo
        state: present
        regexp: "^#?@include common-auth"
        line: "@include common-auth-duo"
        create: no
      when: duo_pam_use_sudo|bool

- name: configure PAM manually
  debug:
    msg: "Duo Unix via PAM must be configured manually to avoid creating an insecure host."
  when: duo_pam_manual_config|bool

  ### NOTE: Some useful information on PAM
  #
  # An amusing, but useful, introduction to PAM
  #   https://www.redhat.com/en/blog/pam-%E2%80%93-pluggable-authentication-modules-linux-and-how-edit-defaults
  #
  # General intro and overview of PAM
  #   https://documentation.suse.com/sled/15-SP1/html/SLED-all/cha-pam.html
  #

